### ISSUE TITLE
Issue with Exporting Identity Cloud Tenant Themes using fr-config-manager 1.4.6 in Jenkins

### ISSUE THREAD

**Issue by sarth356** [ForgeRock/fr-config-manager#199]
Hi,

We are encountering the following error while attempting to export our Identity Cloud tenant static repository using Jenkins:

```
11:09:23  + /home/jenkins/.nvm/versions/node/v16.18.1/bin/fr-config-pull all-static
11:09:23  Getting email templates
11:09:23  Getting email provider settings
11:09:23  Getting managed objects
11:09:23  Getting scripts
11:09:23  Getting journeys
11:09:23  Getting endpoints
11:09:23  Getting schedules
11:09:23  Getting connectors
11:09:23  Getting mappings
11:09:23  Getting access config
11:09:23  Getting cors config
11:09:23  Getting password policy
11:09:23  Getting themes
11:09:23  Getting terms and conditions
11:09:23  Getting KBA
11:09:23  Getting services
11:09:23  Getting authentication config
11:09:23  Getting RCS config
11:09:23  Getting UI config
11:09:23  Getting locales
11:09:23  Getting audit settings
11:09:23  Getting org privileges config
11:09:24  TypeError: themes.forEach is not a function
11:09:24      at processThemes (/fr-frconfigmgr/fr-config-manager/packages/fr-config-pull/src/scripts/themes.js:18:12)
11:09:24      at Object.exportThemes (/fr-frconfigmgr/fr-config-manager/packages/fr-config-pull/src/scripts/themes.js:103:7)
11:09:24      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
We are using fr-config-manager version 1.4.6. Could you please assist us in resolving this issue or suggest any workarounds?
Additionally, in our Jenkins setup, we are using Node.js version 16.18.1. Is there a recommended version that we should be using for compatibility with the fr-config-manager?
We also noticed a similar issue was opened in the past (referenced here: https://github.com/ForgeRock/fr-config-manager/issues/196), which has since been closed. However, we are facing a similar issue now.

**Comment by christian-brindley** [comment]
It looks like themes can have a null value for a realm, as well as a missing realm. I have updated to fix both situations - in the main branch as version 1.4.7-beta.1. We'll put this into its own release if this fixes the issue.

One workaround is to go into both realms in the UI and save one theme in each, to repopulate the null realm.
