### ISSUE TITLE
fr-config-push endpoints command fails with 'The "cb" argument must be of type function' error

### ISSUE THREAD

**Issue by dragos-panaitescu-fr** [ForgeRock/fr-config-manager#33]
The fr-config-push endpoints command is failing with 'The "cb" argument must be of type function' error.

Complete error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "cb" argument must be of type function. Received undefined
    at maybeCallback (node:fs:174:3)
    at Object.readFile (node:fs:377:14)
    at /home/runner/xxx/fr-config-manager/packages/fr-config-push/src/scripts/update-idm-endpoints.js:[47](xxx#step:6:48):20
    at f (/home/runner/work/xxx/fr-config-manager/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:1[48](xxx#step:6:49):7)
    at Glob.emit (node:events:[51](xxx/actions/runs/5963881286/job/16177970344#step:6:52)3:28)
    at Glob._finish (/home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:194:8)
    at done (/home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:179:14)
    at Glob._processReaddir2 (/home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:434:12)
    at /home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:371:17
    at RES (/home/runner/work/xxx/fr-config-manager/node_modules/inflight/inflight.js:31:16)
    at f (/home/runner/work/xxx/fr-config-manager/node_modules/once/once.js:25:25)
    at Glob._readdirEntries (/home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:578:10)
    at /home/runner/work/xxx/fr-config-manager/node_modules/glob/glob.js:[55](xxx#step:6:56)5:12
    at FSReqCallback.oncomplete (node:fs:185:23) ***
  code: 'ERR_INVALID_ARG_TYPE'`

Error is triggered by this line:
`await fs.readFile(path.join(dir, fileContent))`

fs.readFile async function requires a third parameter as a Callback function

Should be replaced with synchronous function:
`await fs.readFileSync(path.join(dir, fileContent))`

**Comment by dragos-panaitescu-fr** [comment]
Also found a second error in the same endpoints script.

This line is throwing 'readFyleSync is not defined':
`const data = readFileSync(`${dir}/${endpoint.file}`, "utf8");`

Should be:
`const data = fs.readFileSync(`${dir}/${endpoint.file}`, "utf8");`

**Comment by dragos-panaitescu-fr** [comment]
Created PR for issue: https://github.com/ForgeRock/fr-config-manager/pull/34
